### PR TITLE
Add Tekton Results Logo

### PR DESCRIPTION
**Pull request by fdegir**
Closes cdfoundation/foundation#440

### CODE REVIEW

**Review by adambkaplan — CHANGES_REQUESTED** [review]
`.ai` is an Adobe Illustrator file. I don't see other artwork storing an Illustrator file - ok to drop this?

**Comment by fdegir** [comment]
@adambkaplan done!

**Review by adambkaplan — APPROVED** [review]
Squash commits, and I think this is good to merge (otherwise the illustrator files will show up in the git history).

**Pull request merged**
