### PR TITLE
Adds artwork for Pyrsia

### PR DESCRIPTION
**Pull request by betarelease**

### CODE REVIEW

**Comment by zestyroxy** [comment]
Thank you @betarelease. It is possible to rename some of these (the ones all called "Group_#"?)

**Comment by betarelease** [comment]
I will make that change and update the PR @zestyroxy

**Comment by betarelease** [comment]
Done @zestyroxy

**Comment by zestyroxy** [comment]
Thanks @betarelease.

It would also be great if you could also add them to the read me table on this page: https://github.com/cdfoundation/artwork

**Pull request merged**
