### PR TITLE
Update shipwright logos

### LINKED ISSUE #37: Add Shipwright Logos
Shipwright's logos are missing from the artwork page.

The official assets can be found on the project's community repository: https://github.com/shipwright-io/community/tree/main/assets/icons/png

### PR DESCRIPTION
**Pull request by adambkaplan**
- Add Shipwright logos in standard formats and colors
  - Horizontal, icon, and stacked
  - Black, white, and color
  - .png and .svg formats
- Update README to include Shipwright logos.
- Remove old Shipwright icons

Fixes #37

### CODE REVIEW

**Comment by adambkaplan** [comment]
@zestyroxy I think this will fix the logo issue we had for Shipwright.

**Comment by zestyroxy** [comment]
Thanks! You can copy this commit from [Screwdriver](https://github.com/cdfoundation/artwork/pull/36/commits) if that helps :)

**Comment by zestyroxy** [comment]
Whatever is easier for you :)

**Comment by adambkaplan** [comment]
@zestyroxy squashed, message updated.

**Comment by zestyroxy** [comment]
Awesome, thank you!

**Pull request merged**
